- job:
    name: "image-busybox"
    concurrent: false
    description: Busybox images for LXC and LXD.
    node: master
    project-type: matrix

    axes:
    - axis:
        name: architecture
        type: slave
        values:
        - amd64
        - arm64

    - axis:
        name: release
        type: user-defined
        values:
        - "1.34.1"

    - axis:
        name: variant
        type: user-defined
        values:
        - default

    builders:
    - shell: |-
        cd /lxc-ci
        LXD_ARCHITECTURE="${architecture}"
        ARCH=${architecture}
        TYPE=container

        exec sudo /lxc-ci/bin/build-distro /lxc-ci/images/busybox.yaml \
            ${LXD_ARCHITECTURE} ${TYPE} 1200 ${WORKSPACE} \
            -o image.architecture=${ARCH} -o image.release=${release}

    properties:
    - build-discarder:
        num-to-keep: 3

    - raw:
        !include: ../includes/webhook.yaml.inc

    publishers:
    - archive:
        artifacts: "*.qcow2,*.tar.xz,*.squashfs,image.yaml,serial"
        only-if-success: true

    - workspace-cleanup:
        fail-build: false


    - naginator:
        rerun-unstable-builds: true
        rerun-matrix-part: true
        max-failed-builds: 3
        progressive-delay-increment: 300
        progressive-delay-maximum: 900

    triggers:
    - timed: '@daily'

    wrappers:
    - ansicolor:
        colormap: css
